/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.xperi.schema.metadata;
@org.apache.avro.specific.AvroGenerated
public enum Operations implements org.apache.avro.generic.GenericEnumSymbol<Operations> {
  CREATE, UPDATE, DELETE  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Operations\",\"namespace\":\"com.xperi.schema.metadata\",\"symbols\":[\"CREATE\",\"UPDATE\",\"DELETE\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
