/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.xperi.schema.subjobevent;
@org.apache.avro.specific.AvroGenerated
public enum AssetCategory implements org.apache.avro.generic.GenericEnumSymbol<AssetCategory> {
  METADATA, ASSET  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AssetCategory\",\"namespace\":\"com.xperi.schema.subjobevent\",\"symbols\":[\"METADATA\",\"ASSET\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
